# -*- coding: utf-8 -*-
"""EfectoDeMareas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhpMgCCszLihds1AdvXBBrBV1QkPxNNk

## ¿Que pasaria si cambio la masa solar de 1 metro solar a 2 metros solares? del efecto de mareas

## ¿Que pasaria si cambio la masa solar de 1 metro solar a 2 metros solares? del efecto de mareas

# Procedimiento

El simulador ya esta configurado para que el sol tena 1 masa solar, lo unico que hare es cambiar ese unico valor a 2 y registrar en una hoja de excel, los cambios en en planeta tierra.

Se usara un temporizador y se registraran los datos en intervalos de 1 minuto.
Cada minuto que pasa, pauso la simulacion, lo registro y continuo. Asi, 20 veces.

Los datos se registran en el tablero "resumen" de los resultados.
La velocidad configurada para Universe Sandox de la dinamica de la simulacion es de 16.5 dia por segundo.

ADVERTENCIA


1.  Simplificaciones y aproximaciones: Universe Sandbox utiliza modelos y  algoritmos simplificados para simular fenómenos astronómicos. Estas simplificaciones pueden implicar supuestos y aproximaciones que no reflejan completamente la complejidad de los eventos reales. Por lo tanto, los resultados obtenidos en la simulación pueden diferir de los observados en la realidad.
2.   Precisión y datos actualizados: Los datos y parámetros utilizados en Universe Sandbox se basan en información científica conocida hasta la fecha de desarrollo del programa. Sin embargo, la ciencia y la astronomía están en constante evolución, y nuevos descubrimientos pueden modificar o agregar conocimientos sobre el universo. Por lo tanto, algunos datos o características específicas de objetos astronómicos pueden no ser completamente precisos o actualizados en la simulación.

3. Precisión y datos actualizados: Los datos y parámetros utilizados en Universe Sandbox se basan en información científica conocida hasta la fecha de desarrollo del programa. Sin embargo, la ciencia y la astronomía están en constante evolución, y nuevos descubrimientos pueden modificar o agregar conocimientos sobre el universo. Por lo tanto, algunos datos o características específicas de objetos astronómicos pueden no ser completamente precisos o actualizados en la simulación.

4. Interacciones simplificadas: Aunque Universe Sandbox simula interacciones gravitatorias y otros fenómenos astronómicos, es importante tener en cuenta que el programa utiliza modelos simplificados para representar estas interacciones. Las complejidades del universo real, como la interacción entre múltiples cuerpos celestes, pueden ser difíciles de simular con precisión absoluta en un entorno virtual.

5. Interpretación y extrapolación: Al realizar análisis y conclusiones basados en las simulaciones de Universe Sandbox, es fundamental comprender que la extrapolación de resultados y la interpretación de los fenómenos simulados deben hacerse con cautela. Los resultados obtenidos en la simulación no deben tomarse como evidencia científica concluyente sin realizar investigaciones adicionales y consultar fuentes científicas confiables.

# LIBRERIAS-BOOKCASES
"""

!pip install empiricaldist

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import scipy.stats
from empiricaldist import Pmf, Cdf
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats as ss

"""DEFINICIONES

Radio solar, R☉:
Radio limite de Roche x, y, z:
Magnitud de la tension de marea, GN:
Efecto termico de marea, TW:

# BASE DE DATOS - DATABASE
"""

exp= pd.read_csv("/content/ExperimentoMareas.csv")
exp

"""# Colecta y validación de datos - Data collection and validation

¿Qué tipo de dato son las variables del conjunto de datos? - What type of data are the variables in the data set?
"""

(
    exp
 .dtypes
 .value_counts()
)

"""¿Cuántas variables de cada tipo de dato tenemos en el conjunto de datos? - How many variables of each data type do we have in the data set?"""

exp.shape

"""¿Existen valores nulos explícitos en un conjunto de datos? - Are there explicit null values ​​in a data set?"""

(
    exp
 .isnull()
 .any()
)

"""Como podemos ver, la base de datos no tiene valores nulos

# CONTEOS Y PROPORCIONES - COUNTS AND PROPORTIONS

Todas las variables - all variables
"""

exp.describe(include= "all")

"""Me interesa ver el efecto termico de marea -
I'm interested in seeing the tidal thermal effect
"""

sns.catplot(
    data=exp,
    x="efecto_termico_marea",
    kind="count",
    height=10,
)

"""
# MEASURES OF CENTRAL TENDENCY - medidas de tendencia central"""

media= exp.mean()
media

exp.median()

exp.mode()

"""# MEDIDAS DE DISPERCION"""

exp.max()

exp.min()

exp.max(numeric_only=True)-exp.min(numeric_only=True)

exp.std()

exp.quantile()

"""Distribucion de las variables del efecto termico de la marea"""

exp.quantile()

rankquantile= (
    exp
 .quantile(q=[0.75,0.50,0.25])
 .transpose()
 .rename_axis("variable")
 .reset_index()
 .assign(
    iqr=lambda NameFunction3: NameFunction3[0.75]-NameFunction3[0.25]
 )
)
rankquantile

sns.boxplot(
    data=rankquantile,



)

"""# DISTRIBUCIONES - DISTRIBUTIONS

Funciones de probabilidad de masas - Mass probability functions
"""

sns.histplot(
    data=exp,
    x="efecto_termico_marea",
    binwidth=50,
    stat="probability"
)

"""Funciones empíricas de probabilidad acumulada - Empirical cumulative probability functions"""

sns.ecdfplot(
    data=exp,
    x="efecto_termico_marea",
)

"""Voy a comparar el efecto termico de marea con la magnitud_tension_marea"""

sns.ecdfplot(
    data=exp,
    x="efecto_termico_marea",
    hue="magnitud_tension_marea",

)

"""FUNCIONES DE DENSIDAD DE PROBABILIDAD - PROBABILITY DENSITY FUNCTIONS"""

sns.kdeplot(
    data=exp,
    x="efecto_termico_marea",

)

"""# ANALISIS BIVARIADO - BIVARIATE ANALYSIS

Estableciendo relaciones

Quiero ver la relacion que tiene el efecto termico de marea con la magnitud de tension de la marea - I want to see the relationship that the tidal thermal effect has with the magnitude of tidal stress
"""

sns.scatterplot(
    data=exp,
    x="efecto_termico_marea",
    y="magnitud_tension_marea",
    alpha=1,
    s=20
)

"""Quiero ver la relacion del efecto termico de marea con el limite de roche en eje x -
I want to see the relationship of the tidal thermal effect with the Roche limit in x axis
"""

sns.scatterplot(
    data=exp,
    x="efecto_termico_marea",
    y="r_ limit_ roche_ X",
    alpha=1,
    s=20
)

sns.scatterplot(
    data=exp,
    x="efecto_termico_marea",
    y="r_ limit_ roche_ Y",
    alpha=1,
    s=20
)

"""# MATRICES DE CORRELACION - CORRELATION MATRIX"""

exp_corr= exp.corr()
exp_corr

sns.heatmap(
    data=exp_corr.corr(),
    cmap=sns.diverging_palette(20,230,as_cmap=True),
    center=0,
    vmin=0,
    vmax=1,
    linewidths=0.5,
    annot=True,

)

"""# SIMPLE REGRESSION ANALYSIS - ANALISIS DE REGRESION SIMPLE"""

sns.scatterplot(
    data=exp,
    x="efecto_termico_marea",
    y="r_ limit_ roche_ X",
)

sns.lmplot(
    data=exp,
    x="efecto_termico_marea",
    y="r_ limit_ roche_ X",
    height=10
)

sns.lmplot(
    data=exp,
    x="r_ limit_ roche_ Z",
    y="r_ limit_ roche_ X",
    height=10
)

"""# ANALISIS MULTIVARIADO - MULTIVARIATE ANALYSIS"""

model1= (
    smf.ols(
        data=exp,
        formula="efecto_termico_marea ~ magnitud_tension_marea",

    )
    .fit()
)
model1.summary()

modelos_resultados= pd.DataFrame(
    dict(
        actual_value=exp.efecto_termico_marea,
         prediction_model1= model1.predict(),

    )
)
modelos_resultados

sns.barplot(
    data= modelos_resultados
)

"""ECDFs"""

sns.ecdfplot(
    data=modelos_resultados
)

sns.kdeplot(
    data=modelos_resultados
)

"""ANALISIS DE REGRESION LOGISTICA - LOGISTIC REGRESSION ANALYSIS"""

smf.mnlogit(
    formula="efecto_termico_marea ~ magnitud_tension_marea",
    data=exp,

).fit().summary()